### ISSUE TITLE
reveal v4.1.1  Reveal.getConfig is not a function 

### ISSUE THREAD

**Issue by steven-varga** [satoshifuku/handwriting#10]
Do you happened to know if it works with `reveal v4.1.1`?  

```
Uncaught TypeError: Reveal.getConfig is not a function
    at resetStorages (handwriting.js:117)
    at handwriting.js:113
    at handwriting.js:712
(index):88 Uncaught ReferenceError: RevealHandWriting is not defined
    at (index):88
DevTools failed to load source map: Could not load content for http://0.0.0.0:8000/dist/reveal.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```
